spring:
  application:
    name: routing-service

logging:
  level:
    dev.tpcoder.routing: debug

# http://localhost:8081/api/v1/echo,http://localhost:8082/api/v1/echo,http://localhost:8083/api/v1/echo
routing:
  health-check:
    interval: 10s
  upstream:
    hosts: ${CONFIG_DOWNSTREAM_HOSTS:http://localhost:8081/api/v1/echo,http://localhost:8082/api/v1/echo,http://localhost:8083/api/v1/echo}
    timeout: 500ms
    failure-attempt-threshold: 2